In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import NearestNeighbors, KNeighborsClassifier

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
print train.head()
print test.head()

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
   Passe

In [2]:
train_X = train[['Sex', 'Age', 'SibSp', 'Pclass', 'Fare', 'Parch', 'Embarked']]   # the columns which affect the survival
test_X = test[['Sex', 'Age', 'SibSp', 'Pclass', 'Fare', 'Parch', 'Embarked']]
train_y = train['Survived']
train_X.loc[:, 'Sex'] = train_X['Sex'].astype('category')
train_X.loc[:, 'Embarked'] = train_X['Embarked'].astype('category')
test_X.loc[:, 'Sex'] = test_X['Sex'].astype('category')
test_X.loc[:, 'Embarked'] = test_X['Embarked'].astype('category')

# Selecting the category columns
train_X_cat_cols = train_X.select_dtypes(['category']).columns
train_X[train_X_cat_cols] = train_X[train_X_cat_cols].apply(lambda x : x.cat.codes) 
test_X[train_X_cat_cols] = test_X[train_X_cat_cols].apply(lambda x : x.cat.codes) 

/Users/spreeth/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:426: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/Users/spreeth/anaconda/lib/python2.7/site-packages/pandas/core/frame.py:2320: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]


In [3]:
def LogRegModel(X, y, C) :
    theta = np.zeros(1, (X.size(1)))
    def Hypothesis (y, yhat):
        return np.exp(- np.dot((y-yhat), (y-yhat))/2)
                     
    def CostFunction(X, y):
        yhat
        return -(np.dot(y, np.log(Hypothesis(y, yhat))) + 
                        np.dot(1-y, np.log(1-Hypothesis(y, yhat))))

    def Optimization():

    

from sklearn.cross_validation import cross_val_score
train_X = train_X.fillna(train_X.mean()['Age'])
test_X = test_X.fillna(test_X.mean()['Age'])

train_X_sub = train_X[['Sex', 'Age', 'Pclass', 'Fare']]
train_X_sub['Sibsp+Parch'] = train_X['Parch'] + train_X['SibSp']

rfc = RandomForestClassifier(random_state=123)
gnb = GaussianNB()
logreg = LogisticRegression(C=1e1, random_state=123)
eclf = VotingClassifier(estimators=[('lr', logreg), ('rf', rfc)],
                        voting='soft',
                        weights=[1, 2])

logreg = logreg.fit(train_X.values, train_y.values)
eclf = eclf.fit(train_X.values, train_y.values)
rfc = rfc.fit(train_X.values, train_y.values)
cross_vals = cross_val_score(logreg, train_X.values, train_y.values, cv=5)
cross_vals_eclf = cross_val_score(eclf, train_X.values, train_y.values, cv=5)
cross_vals_rfc = cross_val_score(rfc, train_X.values, train_y.values, cv=5)

print cross_vals
print cross_vals_eclf
print cross_vals_rfc

[ 0.77094972  0.7877095   0.78089888  0.76404494  0.81920904]
[ 0.79888268  0.80446927  0.83146067  0.81460674  0.80225989]
[ 0.7877095   0.79888268  0.81460674  0.78651685  0.78531073]


/Users/spreeth/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [4]:
logreg_decision_fn = logreg.decision_function(test_X.values)

In [7]:
neigh = KNeighborsClassifier(n_neighbors=3)
cross_vals_nn = cross_val_score(neigh, train_X.values, train_y.values, cv=5)
print cross_vals_nn
neigh = neigh.fit(train_X.values, train_y.values)

[ 0.64804469  0.73184358  0.71910112  0.73595506  0.69491525]


2.7182818284590451